[detection]
dependencies = ["@angular/core", "@angular/build"]
files = ["angular.json"]

[entry_points]
dirs = []
files = ["angular.json"]

[magic_exports]
names = []

[tooling_deps]
names = ["@angular/cli"]
