//! sql-no-serial-use-identity

mod text;

use crate::diagnostic::Severity;
use crate::files::Language;
use crate::rules::RuleDef;
use crate::rules::backend::Backend;
use crate::rules::meta::RuleMeta;

pub const META: RuleMeta = RuleMeta {
    id: "sql-no-serial-use-identity",
    description: "`SERIAL`/`BIGSERIAL`/`SMALLSERIAL` create implicit sequences with surprising ownership and permission semantics.",
    remediation: "Use `GENERATED ALWAYS AS IDENTITY` (or `GENERATED BY DEFAULT AS IDENTITY`). Identity columns are SQL-standard, own their sequences cleanly, and survive `pg_dump --data-only` correctly.",
    severity: Severity::Warning,
    doc_url: None,
    categories: &["database", "sql"],
};

pub fn register() -> RuleDef {
    RuleDef {
        meta: META,
        backends: vec![(Language::Sql, Backend::Text(Box::new(text::Check)))],
    }
}
