//! E2E tests for each lint rule's detection logic.

mod common;

use assert_cmd::Command;
use common::write_ts_file;
use predicates::prelude::*;

#[test]
fn detects_nested_ternary_violation() {
    let (_dir, path) = write_ts_file("ternary.ts", "export const x = a ? b ? 1 : 2 : 3;\n");
    Command::cargo_bin("comply")
        .unwrap()
        .arg(&path)
        .assert()
        .stdout(predicate::str::contains("no-nested-ternary"));
}

#[test]
fn detects_banned_identifier() {
    let (_dir, path) = write_ts_file("banned.ts", "function processOrder() { return 1; }\n");
    Command::cargo_bin("comply")
        .unwrap()
        .arg(&path)
        .assert()
        .stdout(predicate::str::contains("no-generic-names"))
        .stdout(predicate::str::contains("processOrder"));
}

#[test]
fn detects_nested_ternary() {
    let (_dir, path) = write_ts_file("ternary.ts", "const x = a ? b ? 1 : 2 : 3;\n");
    Command::cargo_bin("comply")
        .unwrap()
        .arg(&path)
        .assert()
        .stdout(predicate::str::contains("no-nested-ternary"));
}

#[test]
fn multiple_violations_are_all_reported() {
    let source = "function processOrder() { const y = a ? b ? 1 : 2 : 3; }\n";
    let (_dir, path) = write_ts_file("multi.ts", source);
    Command::cargo_bin("comply")
        .unwrap()
        .arg(&path)
        .assert()
        .code(1)
        .stdout(predicate::str::contains("no-nested-ternary"))
        .stdout(predicate::str::contains("no-generic-names"));
}

#[test]
fn homemade_async_state_is_reported() {
    let source = "export type Status = \"idle\" | \"loading\" | \"error\";\n";
    let (_dir, path) = write_ts_file("status.ts", source);
    Command::cargo_bin("comply")
        .unwrap()
        .arg(&path)
        .assert()
        .stdout(predicate::str::contains("no-homemade-async-state-union"));
}

#[test]
fn homemade_async_state_is_skipped_in_a_generated_file() {
    // The engine drops generated files before any rule runs; this pins that
    // the rule inherits that exemption rather than re-implementing it.
    let source = "// @generated by openapi-typescript\nexport type Status = \"idle\" | \"loading\";\n";
    let (_dir, path) = write_ts_file("generated-status.ts", source);
    Command::cargo_bin("comply")
        .unwrap()
        .arg(&path)
        .assert()
        .stdout(predicate::str::contains("no-homemade-async-state-union").not());
}
