//! Translate per-clippy-lint thresholds in `comply.toml` into a
//! temporary `clippy.toml` that we point clippy at via `CLIPPY_CONF_DIR`.
//!
//! Why a separate file: clippy reads its own configuration (thresholds,
//! allow-lists, etc.) exclusively from a `clippy.toml` next to the
//! `Cargo.toml` it runs against. There's no command-line equivalent
//! for most of the keys. So if a user writes
//!
//!     [rules."clippy::too_many_lines"]
//!     threshold = 50
//!
//! in their `comply.toml`, comply has to materialize a `clippy.toml`
//! containing `too-many-lines-threshold = 50` somewhere clippy will
//! find it. We can't write the user's project root because they may
//! already have one — so we write to a temp dir and pass
//! `CLIPPY_CONF_DIR=<that-dir>` to the cargo subprocess.
//!
//! The mapping from `[rules."clippy::xxx"]` to `clippy.toml` keys is
//! the auto-generated `all_args::CLIPPY_THRESHOLD_LINTS` table.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

use super::all_args::{ArgKind, ClippyArg, CLIPPY_THRESHOLD_LINTS};
use crate::config::Config;

/// Build the body of a temporary `clippy.toml` from the user's
/// per-lint thresholds. Returns `None` when the user hasn't set any
/// threshold — the caller can then skip the temp-dir + env-var dance.
#[must_use]
pub fn render_clippy_toml(config: &Config) -> Option<String> {
    let mut lines: Vec<String> = Vec::new();

    for (rule_id, rule) in config.iter_rules() {
        // Only `clippy::*` rules are eligible for the threshold mapping;
        // tree-sitter and oxlint rules have nothing to do with clippy's
        // own configuration file.
        if !rule_id.starts_with("clippy::") {
            continue;
        }
        let Some(arg) = lookup_arg(rule_id) else {
            continue;
        };
        let value_key = match arg.kind {
            ArgKind::Int | ArgKind::String => "threshold",
            ArgKind::Array => "values",
        };
        let Some(value) = rule.extra.get(value_key) else {
            continue;
        };
        if let Some(line) = encode_arg(arg, value) {
            lines.push(line);
        }
    }

    if lines.is_empty() {
        None
    } else {
        let header = "# generated by comply — do not edit by hand.\n\
                      # This file is materialized in a temp dir and passed to\n\
                      # `cargo clippy` via the CLIPPY_CONF_DIR env var.\n";
        Some(format!("{header}{}\n", lines.join("\n")))
    }
}

/// Materialize the rendered `clippy.toml` into a temporary directory.
/// Returns the temp dir handle (which deletes itself on Drop) and
/// the absolute path of the dir for use in `CLIPPY_CONF_DIR`.
pub fn materialize(config: &Config) -> Result<Option<(tempfile::TempDir, PathBuf)>> {
    let Some(body) = render_clippy_toml(config) else {
        return Ok(None);
    };
    let dir = tempfile::tempdir().context("failed to create temp dir for clippy.toml")?;
    let path = dir.path().join("clippy.toml");
    std::fs::write(&path, body).context("failed to write temp clippy.toml")?;
    let dir_path = dir.path().to_path_buf();
    Ok(Some((dir, dir_path)))
}

fn lookup_arg(rule_id: &str) -> Option<&'static ClippyArg> {
    CLIPPY_THRESHOLD_LINTS.iter().find(|a| a.lint == rule_id)
}

/// Render one TOML key/value line for a clippy threshold. Returns
/// `None` when the user's value doesn't fit the expected shape (e.g.
/// they wrote a string for an int knob).
fn encode_arg(arg: &ClippyArg, value: &toml::Value) -> Option<String> {
    let key = arg.clippy_toml_key;
    match arg.kind {
        ArgKind::Int => {
            let n = value.as_integer()?;
            Some(format!("{key} = {n}"))
        }
        ArgKind::String => {
            let s = value.as_str()?;
            Some(format!("{key} = \"{}\"", escape_toml_string(s)))
        }
        ArgKind::Array => {
            let arr = value.as_array()?;
            let items: Vec<String> = arr
                .iter()
                .filter_map(|v| v.as_str())
                .map(|s| format!("\"{}\"", escape_toml_string(s)))
                .collect();
            Some(format!("{key} = [{}]", items.join(", ")))
        }
    }
}

fn escape_toml_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Cargo expects `CLIPPY_CONF_DIR` to point to a directory containing
/// `clippy.toml`, not to the file itself. This helper exists so the
/// callers don't have to remember.
#[must_use]
pub fn env_var_for_dir(dir: &Path) -> (String, String) {
    ("CLIPPY_CONF_DIR".to_string(), dir.display().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;
    use std::fs;
    use tempfile::TempDir;

    fn config_with(toml_text: &str) -> Config {
        let tmp = TempDir::new().unwrap();
        let cfg_path = tmp.path().join("comply.toml");
        fs::write(&cfg_path, toml_text).unwrap();
        let cfg = Config::load_from(tmp.path()).unwrap();
        // Leak the tempdir so the test config keeps the file alive —
        // we only need the parsed Config, not the original on-disk file.
        std::mem::forget(tmp);
        cfg
    }

    #[test]
    fn renders_int_threshold_for_too_many_lines() {
        let cfg = config_with(
            r#"
            [rules."clippy::too_many_lines"]
            threshold = 50
            "#,
        );
        let body = render_clippy_toml(&cfg).expect("must render");
        assert!(body.contains("too-many-lines-threshold = 50"));
    }

    #[test]
    fn renders_array_threshold_for_disallowed_names() {
        let cfg = config_with(
            r#"
            [rules."clippy::disallowed_names"]
            values = ["foo", "bar", "baz"]
            "#,
        );
        let body = render_clippy_toml(&cfg).expect("must render");
        assert!(body.contains("disallowed-names = [\"foo\", \"bar\", \"baz\"]"));
    }

    #[test]
    fn returns_none_when_no_clippy_thresholds_present() {
        let cfg = config_with(
            r#"
            [rules.max-function-lines]
            max = 60
            "#,
        );
        assert!(render_clippy_toml(&cfg).is_none());
    }

    #[test]
    fn ignores_unknown_clippy_lint_keys() {
        let cfg = config_with(
            r#"
            [rules."clippy::needless_borrow"]
            threshold = 99
            "#,
        );
        // `needless_borrow` has no threshold in our table — skip it.
        assert!(render_clippy_toml(&cfg).is_none());
    }
}
