#!/usr/bin/env python3
"""
Regenerate `src/clippy/all_lints.rs` and `src/clippy/all_args.rs`
from the live `cargo clippy -- -W help` output and the upstream
clippy.toml schema.

Why a script and not a build.rs:
  - The output is committed to git so consumers of comply can
    inspect (and grep) every clippy lint comply knows about.
  - It only needs to be regenerated when the toolchain bumps clippy
    or adds new lints. Running it on every build would slow down
    incremental compiles for no benefit.

Run from the repo root:
    python3 scripts/regen-clippy-lints.py
or:
    ./scripts/regen-clippy-lints.py

Outputs:
  src/clippy/all_lints.rs   — every (lint_name, default_level) pair
  src/clippy/all_args.rs    — known threshold-bearing lints + their
                               clippy.toml configuration keys
"""

import subprocess
import sys
import re
from pathlib import Path
from textwrap import dedent

# ----------------------------------------------------------------------------
# Step 1: enumerate every clippy lint via `cargo clippy -- -W help`.
# ----------------------------------------------------------------------------

LINT_LINE = re.compile(
    r"^\s*(clippy::[a-z0-9_-]+)\s+(allow|warn|deny|forbid)\b"
)


def run_clippy_help() -> str:
    """Run `cargo clippy -- -W help` and return the combined stdout+stderr.
    Cargo emits the lint dump on stderr; we capture both to be safe."""
    proc = subprocess.run(
        ["cargo", "clippy", "--quiet", "--", "-W", "help"],
        capture_output=True,
        text=True,
        check=False,  # clippy may exit non-zero; we still want the dump
    )
    return proc.stdout + "\n" + proc.stderr


def parse_lints(text: str) -> list[tuple[str, str]]:
    """Parse `cargo clippy -W help` text. Returns a sorted list of
    (snake_case_lint_name, default_level) tuples. Snake-cases the
    name because clippy accepts both kebab and snake but the in-source
    convention is snake."""
    seen: dict[str, str] = {}
    for line in text.splitlines():
        m = LINT_LINE.match(line)
        if not m:
            continue
        kebab = m.group(1)
        snake = kebab.replace("-", "_")
        seen[snake] = m.group(2)
    return sorted(seen.items())


# ----------------------------------------------------------------------------
# Step 2: hardcoded list of threshold-bearing clippy lints + their
# clippy.toml configuration keys. Extracted from the clippy book at
# https://rust-lang.github.io/rust-clippy/master/index.html
#
# Format: (lint_name, clippy_toml_key, value_kind)
# `value_kind` is one of: "int", "string", "array".
#
# When the user puts e.g. `[rules."clippy::too_many_lines"] threshold = 30`
# in their comply.toml, the clippy module will translate that into
# `too-many-lines-threshold = 30` in the generated clippy.toml.
# ----------------------------------------------------------------------------

THRESHOLD_LINTS: list[tuple[str, str, str]] = [
    # Numeric thresholds
    ("clippy::too_many_lines", "too-many-lines-threshold", "int"),
    ("clippy::too_many_arguments", "too-many-arguments-threshold", "int"),
    ("clippy::large_enum_variant", "enum-variant-size-threshold", "int"),
    ("clippy::large_stack_arrays", "stack-size-threshold", "int"),
    ("clippy::large_stack_frames", "stack-size-threshold", "int"),
    ("clippy::large_types_passed_by_value", "pass-by-value-size-limit", "int"),
    ("clippy::cognitive_complexity", "cognitive-complexity-threshold", "int"),
    ("clippy::excessive_nesting", "excessive-nesting-threshold", "int"),
    ("clippy::min_ident_chars", "min-ident-chars-threshold", "int"),
    ("clippy::single_char_lifetime_names", "single-char-binding-names-threshold", "int"),
    ("clippy::struct_excessive_bools", "max-struct-bools", "int"),
    ("clippy::fn_params_excessive_bools", "max-fn-params-bools", "int"),
    ("clippy::trivial_copy_pass_by_ref", "trivial-copy-size-limit", "int"),
    ("clippy::type_complexity", "type-complexity-threshold", "int"),
    ("clippy::unreadable_literal", "unreadable-literal-lint-fractions", "int"),
    ("clippy::vec_box", "vec-box-size-threshold", "int"),
    ("clippy::verbose_bit_mask", "verbose-bit-mask-threshold", "int"),
    ("clippy::missing_docs_in_private_items", "missing-docs-in-crate-items", "int"),
    # Array thresholds (allowlists)
    ("clippy::disallowed_names", "disallowed-names", "array"),
    ("clippy::doc_markdown", "doc-valid-idents", "array"),
    ("clippy::min_ident_chars", "allowed-idents-below-min-chars", "array"),
]


# ----------------------------------------------------------------------------
# Step 3: generate the Rust files.
# ----------------------------------------------------------------------------

ALL_LINTS_PROLOGUE = dedent(
    """\
    //! Auto-generated by `scripts/regen-clippy-lints.py` — DO NOT EDIT BY HAND.
    //!
    //! Snapshot of every lint clippy advertises via `cargo clippy -- -W help`.
    //! Comply uses this list so a project's `comply.toml` can disable, enable,
    //! or override the severity of any clippy lint without comply having to
    //! ship a per-lint binding for each one.
    //!
    //! Regenerate when the toolchain bumps clippy:
    //!     python3 scripts/regen-clippy-lints.py

    /// Default level a clippy lint fires at when no `-W` / `-A` / `-D` flag
    /// modifies it. Mirrors clippy's `Allow` / `Warn` / `Deny` / `Forbid`.
    #[allow(dead_code)] // Forbid currently unused; keep the variant for future-proofing.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum ClippyDefaultLevel {
        Allow,
        Warn,
        Deny,
        Forbid,
    }

    /// Every clippy lint, indexed by snake_case name. The names match what
    /// clippy emits in its diagnostic JSON output (`clippy::unwrap_used`,
    /// `clippy::needless_borrow`, …) so a `comply.toml` entry like
    /// `[rules."clippy::needless_borrow"] disabled = true` Just Works.
    pub const ALL_CLIPPY_LINTS: &[(&str, ClippyDefaultLevel)] = &[
    """
)

ALL_LINTS_EPILOGUE = "];\n"


def render_all_lints(lints: list[tuple[str, str]]) -> str:
    body = []
    for name, level in lints:
        cap = level.capitalize()
        body.append(f'    ("{name}", ClippyDefaultLevel::{cap}),\n')
    return ALL_LINTS_PROLOGUE + "".join(body) + ALL_LINTS_EPILOGUE


ALL_ARGS_PROLOGUE = dedent(
    """\
    //! Auto-generated by `scripts/regen-clippy-lints.py` — DO NOT EDIT BY HAND.
    //!
    //! Mapping from clippy lint name to its `clippy.toml` configuration key.
    //! Used by `crate::clippy::config_writer` to translate per-lint
    //! thresholds in `comply.toml` (e.g. `[rules."clippy::too_many_lines"]
    //! threshold = 50`) into the right `clippy.toml` line for the temporary
    //! config file we point clippy at.
    //!
    //! Most lints with thresholds use the comply key `threshold`; lints with
    //! list-shaped values (`disallowed_names`, etc.) use the comply key
    //! `values`. The `kind` field tells the writer which TOML shape to emit.

    #[allow(dead_code)] // String is unused today; keep it for future schemas.
    #[derive(Debug, Clone, Copy)]
    pub enum ArgKind {
        Int,
        String,
        Array,
    }

    pub struct ClippyArg {
        pub lint: &'static str,
        pub clippy_toml_key: &'static str,
        pub kind: ArgKind,
    }

    pub const CLIPPY_THRESHOLD_LINTS: &[ClippyArg] = &[
    """
)

ALL_ARGS_EPILOGUE = "];\n"


def render_all_args(args: list[tuple[str, str, str]]) -> str:
    body = []
    for lint, key, kind in args:
        cap = kind.capitalize()
        body.append(
            f'    ClippyArg {{ lint: "{lint}", clippy_toml_key: "{key}", kind: ArgKind::{cap} }},\n'
        )
    return ALL_ARGS_PROLOGUE + "".join(body) + ALL_ARGS_EPILOGUE


# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    target_dir = repo_root / "src" / "clippy"
    if not target_dir.is_dir():
        print(f"error: {target_dir} does not exist", file=sys.stderr)
        return 1

    print("Running cargo clippy -- -W help …")
    text = run_clippy_help()
    lints = parse_lints(text)
    print(f"  found {len(lints)} clippy lints")
    if not lints:
        print("error: parser found zero lints — check the regex / output format",
              file=sys.stderr)
        return 1

    all_lints_path = target_dir / "all_lints.rs"
    all_args_path = target_dir / "all_args.rs"

    all_lints_path.write_text(render_all_lints(lints))
    all_args_path.write_text(render_all_args(THRESHOLD_LINTS))

    print(f"  wrote {all_lints_path.relative_to(repo_root)}")
    print(f"  wrote {all_args_path.relative_to(repo_root)}")
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
