//! `comply catalog` — auto-generated rule catalog grouped by category.
//!
//! Two output modes: markdown (for docs/README) and JSON (for tooling).
//! Categories are hierarchical — a rule with `["typescript", "react"]`
//! appears under "typescript > react" in the markdown output.

use std::collections::BTreeMap;
use std::fmt::Write;

use anyhow::{Context, Result};

use crate::diagnostic::Severity;
use crate::rules;

/// Banner emitted as the first line of the markdown catalog so the checked-in
/// `docs/rules.md` advertises how to regenerate it.
const MARKDOWN_BANNER: &str =
    "<!-- Generated by `comply catalog`. Do not edit by hand; run `comply catalog > docs/rules.md` to regenerate. -->";

/// Generate and print the catalog.
pub fn run(should_emit_json: bool) -> Result<()> {
    let rules = rules::all_rule_defs();
    if should_emit_json {
        print_json(&rules)
    } else {
        print!("{}", markdown_string(&rules));
        Ok(())
    }
}

fn category_label(cats: &[&str]) -> String {
    if cats.is_empty() {
        return "uncategorized".to_string();
    }
    cats.join(" > ")
}

fn severity_str(s: Severity) -> &'static str {
    match s {
        Severity::Error => "error",
        Severity::Warning => "warning",
    }
}

fn backend_label(rule: &rules::RuleDef) -> String {
    use crate::rules::backend::Backend;
    let labels: Vec<&str> = rule
        .backends
        .iter()
        .map(|(_, b)| match b {
            Backend::TreeSitter(_) => "AST",
            Backend::Text(_) => "Text",
            Backend::Oxlint { .. } => "Oxlint",
            Backend::Clippy { .. } => "Clippy",
            Backend::Tsc { .. } => "Tsc",
            Backend::Tsgolint { .. } => "Tsgolint",
            Backend::TypeAware => "TypeAware",
            Backend::Oxc(_) => "Oxc",
        })
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();
    labels.join(", ")
}

/// Render the full markdown catalog as a string. This is the single source of
/// truth for both `comply catalog` stdout and the checked-in `docs/rules.md`.
fn markdown_string(rules: &[rules::RuleDef]) -> String {
    // Group rules by their full category path.
    let mut by_category: BTreeMap<String, Vec<&rules::RuleDef>> = BTreeMap::new();
    for rule in rules {
        let label = category_label(rule.meta.categories);
        by_category.entry(label).or_default().push(rule);
    }

    // Sort rules within each category by id.
    for group in by_category.values_mut() {
        group.sort_by_key(|r| r.meta.id);
    }

    let total = rules.len();
    let mut out = String::new();
    // `write!` to a String is infallible, so the results are unwrapped.
    writeln!(out, "{MARKDOWN_BANNER}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "# comply rule catalog").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "{total} rules across {} categories.", by_category.len()).unwrap();
    writeln!(out).unwrap();

    // Table of contents.
    writeln!(out, "## Categories").unwrap();
    writeln!(out).unwrap();
    for (cat, group) in &by_category {
        let anchor = cat
            .replace(' ', "-")
            .replace('>', "")
            .replace("--", "-")
            .to_lowercase();
        writeln!(out, "- [{cat}](#{anchor}) ({} rules)", group.len()).unwrap();
    }
    writeln!(out).unwrap();

    // Per-category sections.
    for (cat, group) in &by_category {
        writeln!(out, "## {cat}").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "| Rule | Severity | Backend | Description |").unwrap();
        writeln!(out, "|------|----------|---------|-------------|").unwrap();
        for rule in group {
            let id = rule.meta.id;
            let sev = severity_str(rule.meta.severity);
            let backend = backend_label(rule);
            let desc = rule.meta.description;
            writeln!(out, "| `{id}` | {sev} | {backend} | {desc} |").unwrap();
        }
        writeln!(out).unwrap();
    }
    out
}

fn print_json(rules: &[rules::RuleDef]) -> Result<()> {
    let json_rules: Vec<_> = rules
        .iter()
        .map(|r| {
            serde_json::json!({
                "id": r.meta.id,
                "description": r.meta.description,
                "remediation": r.meta.remediation,
                "severity": severity_str(r.meta.severity),
                "categories": r.meta.categories,
                "backend": backend_label(r),
                "docUrl": r.meta.doc_url,
            })
        })
        .collect();

    let output =
        serde_json::to_string_pretty(&json_rules).context("failed to serialize catalog as JSON")?;
    println!("{output}");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn markdown_output_does_not_error() {
        assert!(run(false).is_ok());
    }

    #[test]
    fn json_output_does_not_error() {
        assert!(run(true).is_ok());
    }

    #[test]
    fn docs_rules_md_is_up_to_date() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/docs/rules.md");
        let on_disk = std::fs::read_to_string(path)
            .expect("docs/rules.md is missing; run `comply catalog > docs/rules.md`");
        let expected = markdown_string(&rules::all_rule_defs());
        assert_eq!(
            on_disk, expected,
            "docs/rules.md is stale; regenerate it with `comply catalog > docs/rules.md`"
        );
    }
}
